### ISSUE TITLE
Can't get my head around dx

### ISSUE THREAD

**Issue by TonAtLacework** [partofthething/infopanel#25]
So dx seems to be simple:
- 0 (default) Sprites scroll from left to right
- 1 Sprites scroll from right to left

So why is my text scrolling from left to right and back from right to left no matter what i set the parameter to?

```
  eventdescription:
      type: DynamicFancyText
      #label: 'Description '
      data_label: event_description
      label_color: red
      value_color: white
      font_name: 5x7.bdf
      dx: 1
      ticks_per_movement: 5
```

**Comment by partofthething** [comment]
Oof yeah sorry about that. There's [an undocumented option](https://github.com/partofthething/infopanel/blob/7f04aa0f0fca532c5ea1b53d1c6e5dd6fbc36f0d/infopanel/sprites.py#L95) that defaults to true that you have to add to turn off the 'flipping':

try adding `can_flip: false`

```yaml
  eventdescription:
      type: DynamicFancyText
      #label: 'Description '
      data_label: event_description
      label_color: red
      value_color: white
      font_name: 5x7.bdf
      dx: 1
      ticks_per_movement: 5
      can_flip: false
```
